### ISSUE TITLE
Uncaught TypeError: Cannot read property 'nodeName' of undefined

### ISSUE THREAD

**Issue by dodekeract** [felixerdy/touchbar#13]
### Config:

```json
[
	{
		"command": "project-jump:switch",
		"label": "🔂",
		"name": "switch-project",
		"type": "button"
	},
	{
		"command": "project-jump:add",
		"label": "🔁",
		"name": "add-project",
		"type": "button"
	}
]
```

---

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13
**Thrown From**: [touchbar](https://github.com/felixerdy/touchbar) package 0.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'nodeName' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/command-logger.js:81

TypeError: Cannot read property 'nodeName' of undefined
    at CommandLogger.module.exports.CommandLogger.logCommand (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/command-logger.js:81:44)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/command-logger.js:33:30
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:353:24)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:266:23)
    at click (/packages/touchbar/lib/touchbar.js:107:29)
    at CallbacksRegistry.apply (/Applications/Atom.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:48:42)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:299:21)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:59.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -1:25.6.0 core:move-up (input.hidden-input)
     -1:25.4.0 core:move-right (input.hidden-input)
 10x -1:24.7.0 core:move-up (input.hidden-input)
     -1:15.1.0 editor:consolidate-selections (input.hidden-input)
     -1:15.1.0 core:cancel (input.hidden-input)
     -1:13.2.0 core:move-left (input.hidden-input)
     -1:13.1.0 core:move-down (input.hidden-input)
     -1:12.8.0 core:move-left (input.hidden-input)
     -1:11.6.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
ascii-hex 0.2.0 
atom-alignment 0.13.0 
atom-clock 0.1.15 
atom-css-clean 2.23.0 
atom-ide-ui 0.4.0 
atom-reverser 2.6.0 
atom-sort-sass 0.2.1 
Atom-Syntax-highlighting-for-Sass 0.5.0 
atom-ternjs 0.18.3 
autocomplete-js-import 1.4.0 
autocomplete-json 5.5.0 
autocomplete-module-import 0.1.2 
autoupdate-packages 1.3.1 
base64 0.3.0 
caniuse 0.9.2 
change-case 0.6.5 
change-tabs 0.2.0 
color-picker 2.2.5 
count 2.0.0 
custom-folds 1.9.5 
dash 1.7.1 
edit-in-new-tab 0.10.1 
emmet 2.4.3 
es-identifier-highlight 0.4.3 
file-icons 2.1.12 
flex-tool-bar 0.12.0 
from-and-to-json 1.0.0 
git-control 0.9.0 
git-diff-details 1.4.0 
git-time-machine 1.5.9 
glacier-dark-syntax 0.8.0 
highlight-bad-chars 1.0.7 
highlight-column 0.5.4 
highlight-selected 0.13.1 
http-status-codes 2.0.2 
hyperclick 0.0.0 
ide-typescript 0.6.1 
intentions 1.1.5 
js-hyperclick 1.11.1 
language-babel 2.75.1 
language-docker 1.1.8 
language-dotenv 1.1.1 
language-gitignore 0.3.0 
language-glsl 2.0.2 
language-haskell 1.14.3 
language-ini 1.19.0 
language-latex 1.1.1 
language-nginx 0.8.0 
language-pfm 0.82.0 
language-prolog 0.11.0 
language-swift 0.5.0 
language-webassembly 1.0.1 
language-x86-64-assembly 2.2.11 
linter 2.2.0 
linter-eslint 8.3.2 
linter-gcc 0.7.1 
linter-jsonlint 1.3.0 
linter-markdown 5.2.0 
linter-ui-default 1.6.10 
linter-ui-touchbar 0.2.1 
linter-wast 0.5.3 
linter-write-good 0.9.0 
markdown-preview-plus 2.4.10 
markdown-table-formatter 2.9.0 
markdown-toc 0.4.2 
min-ui 0.0.4 
minimap 4.29.7 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
multi-cursor 2.1.5 
native-ui 0.23.0 
new-fast-duplicate 2.0.0 
node-debugger 1.10.1 
open-path 0.3.6 
pdf-view 0.59.0 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
prettier-atom 0.40.0 
project-jump 0.3.0 
quick-issues 0.9.3 
sorter 1.1.0 
source-preview 0.5.2 
source-preview-markdown 0.1.1 
source-preview-sass 0.1.6 
spacegray-black-syntax 0.1.4 
sunset 1.2.1 
svg-preview 0.11.0 
sync-settings 0.8.3 
tester 1.4.0 
tester-jest 1.1.8 
toggle-markdown-task 0.6.0 
token-navigation 1.5.3 
tool-bar 1.1.0 
touchbar 0.6.0 
touchbar-git 0.1.4 
touchbar-registry 0.3.2 
trailing-spaces 0.4.0 
tree-view-git-status 1.4.0 
url-open 0.1.0 
zentabs 0.8.8 
```

**Comment by dodekeract** [comment]
Thanks for your work!
