### ISSUE TITLE
Uncaught TypeError: Cannot read property 'TouchBarLabel' of undefined

### ISSUE THREAD

**Issue by davidlondono** [felixerdy/touchbar#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.3
**Thrown From**: [touchbar](https://github.com/felixerdy/touchbar) package 0.3.11

### Stack Trace

Uncaught TypeError: Cannot read property 'TouchBarLabel' of undefined

```
At /Users/dalon/.atom/packages/touchbar/lib/touchbar-edit-view.js:7

TypeError: Cannot read property 'TouchBarLabel' of undefined
    at /packages/touchbar/lib/touchbar-edit-view.js:7:81)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/touchbar/lib/touchbar.js:7:25)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:887:35)
    at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:301:18)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:68:20)
    at PackageCard.hasSettings (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:793:40)
    at PackageCard.updateSettingsState (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:438:22)
    at PackageCard.updateInterfaceState (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:430:18)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:727:22
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:810:17
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:687:33)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:526:32
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
  2x -4:02.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-ctags 5.1.0 
build-npm-apm 0.12.0 
busy-signal 1.4.3 
ctags-status 1.3.7 
git-control 0.9.0 
git-plus 7.9.3 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.2 
minimap 4.28.3 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-plus 4.29.2 
minimap-selection 4.4.0 
npm-plus 0.4.0 
project-manager 3.3.5 
script 3.15.0 
sync-settings 0.8.2 
terminal-plus 0.14.5 
touchbar 0.3.11 
tree-view-git-status 1.4.0 
```

**Comment by felixerdy** [comment]
Please notice that the touchbar package currently only runs with atom beta v.1.19
This is due to the used electron version
